add rule Limit db query results
green-code-initiative/ecoCode-javascript pull request #18
Opened 2023-07-20 15:08 UTC by elisecodedestrucs

add a rule that forbids SQL requests that can have an infinite number of returns

2023-07-21 03:40 UTC, dedece35 requested changes
Hi @elisecodedestrucs 
Thank you for your PR ...
I let our JS expert review your PR (@utarwyn), but for me can you add an update of `CHANGELOG.md` file with your modification
One more thing, do you upgrade our real test repository [ecoCode-javascript-test-project](https://github.com/green-code-initiative/ecoCode-javascript-test-project) with a test use case (as your unit test) ?

2023-07-21 19:45 UTC, utarwyn reviewed
Thank you for this first contribution! Great work 💯 
Just a few comments/proposals to make everything 100% clean..

Maybe you can also create an issue with the list the rules you've added to the ESLint plugin that will need to be added to the SonarQube plugin too

2023-07-21 19:45 UTC, utarwyn commented on eslint-plugin/lib/rules/limit-db-query-results.js
> +      description: "Warn about not limiting the number of returns for a query",
```suggestion
      description: "Should limit the number of returns for a SQL query",
```

2023-07-21 19:45 UTC, utarwyn commented on eslint-plugin/lib/rules/limit-db-query-results.js
> +              query.includes("FETCH FIRST")
Maybe store the list of keywords in a constant above?
The goal is to simplify the addition of keywords that limit number of returns in the future :+1:

2023-07-21 19:45 UTC, utarwyn commented on CHANGELOG.md
> +-   Add rule `@ecocode/limit-db-query-results`
Can you put this line in the `unreleased` > `Added` section above? Instead of here

2023-07-22 03:47 UTC, dedece35 commented
HI @elisecodedestrucs, please correct the "branch out-of-date" warning above :p

2023-07-24 09:30 UTC, elisecodedestrucs commented
Hi, Thank you for your returns! 
I have made the requested changes don't hesitate to tell me if there's more

2023-07-24 11:27 UTC, utarwyn commented
@elisecodedestrucs can you also re-run npm script `update:eslint-docs` to update documentation files with the new description I proposed? Apart from that, everything looks good to me!

2023-07-24 18:07 UTC, utarwyn approved these changes

2023-07-25 04:08 UTC, dedece35 approved these changes

2023-07-25 04:12 UTC, dedece35 requested changes
Hi @elisecodedestrucs 
could you please upgrade https://github.com/green-code-initiative/ecoCode-javascript-test-project repository with a test case ?

2023-08-09 20:38 UTC, merged