add rule image-src-attribute-not-empty
green-code-initiative/ecoCode-javascript pull request #19
Opened 2023-07-21 14:44 UTC by elisecodedestrucs

add a rules that forbids the use of <img/> without or with an empty src attribute to save CPU usage.

2023-07-21 15:33 UTC, dedece35 submitted a review, later dismissed

2023-07-23 17:49 UTC, utarwyn requested changes
Thank you for this contribution too! Also few comments on this one..
Can you also run the linter on added files to fix the build?

2023-07-23 17:49 UTC, utarwyn commented on eslint-plugin/docs/rules/image-src-attribute-not-empty.md
> +# Disallow usage of image with empty source attribute (`@ecocode/image-src-attribute-not-empty`)
I suggest to follow conventions and start the rule name by `no-`. But it also impacts name of your files..
```suggestion
# Disallow usage of image with empty source attribute (`@ecocode/no-empty-image-src-attribute`)
```

2023-07-23 17:49 UTC, utarwyn commented on eslint-plugin/tests/lib/rules/image-src-attribute-not-empty.js
> +      <img src='logo.svg' alt='Ceci est une image svg'/>
Can you translate all alternative attributes in this file?
```suggestion
      <img src='logo.svg' alt='This is a SVG image'/>
```

2023-07-23 17:49 UTC, utarwyn commented on eslint-plugin/docs/rules/image-src-attribute-not-empty.md
> +This rule aims to prohibit the usage of <img/> without specifying its source attribute because it causes extra and unnecessary http requests.
Can you explain here that this rule is for React/JSX?

2023-07-25 07:45 UTC, elisecodedestrucs commented
> Thank you for this contribution too! Also few comments on this one.. Can you also run the linter on added files to fix the build?

When I run the linter it raises errors on files I haven't changed, I don't know what to make of it?

2023-07-25 11:57 UTC, utarwyn commented
> @elisecodedestrucs 
> When I run the linter it raises errors on files I haven't changed, I don't know what to make of it?

You can install the prettier plugin in your IDE to format automatically files when you save them ([more info here](https://prettier.io/docs/en/editors.html)).
Otherwise, you can see the errors raised by the build script directly from GitHub [here](https://github.com/green-code-initiative/ecoCode-javascript/pull/19/files#diff-b964b8456c55f83c6988ba5e435eaee6ebfd70d0a5429d2111f28165b872e2b7R39)

2023-08-06 21:12 UTC, utarwyn approved these changes
LGTM :100: Can you also propose a test case for this rule in the test project?

2023-08-09 20:42 UTC, utarwyn requested changes
Can you please correct conflicts? (due to the merge of #18)

2023-08-10 20:08 UTC, utarwyn approved these changes

2023-08-10 20:34 UTC, merged