Add a GitHub workflow to test plugin within SonarQube
green-code-initiative/ecoCode-javascript pull request #54
Opened 2024-10-14 18:10 UTC by utarwyn

2024-10-14 18:54 UTC, utarwyn commented on sonar-plugin/src/main/java/io/ecocode/javascript/checks/AvoidHighAccuracyGeolocation.java
> +// @DeprecatedRuleKey(repositoryKey = "ecocode-javascript", ruleKey = "EC8")
This deprecated rule breaks the SonarQube start.
I hadn't detected it in the PR that covered this topic: I've disabled it here to check that the proof of concept is working properly. Thanks to integration testing, such cases should no longer occur.

2024-10-15 07:00 UTC, dedece35 requested changes

2024-10-15 07:00 UTC, dedece35 commented on sonar-plugin/src/main/java/io/ecocode/javascript/checks/AvoidHighAccuracyGeolocation.java
> +// @DeprecatedRuleKey(repositoryKey = "ecocode-javascript", ruleKey = "EC8")
for me, it's important that it can work with Deprecated annotation ... we have this use case 😰

2024-10-15 07:02 UTC, utarwyn commented on sonar-plugin/src/main/java/io/ecocode/javascript/checks/AvoidHighAccuracyGeolocation.java
> +// @DeprecatedRuleKey(repositoryKey = "ecocode-javascript", ruleKey = "EC8")
yes, as I said this is not normal and I use it in this draft PR to check if the health check works

2024-10-15 07:03 UTC, utarwyn commented on docker-compose.yml
> +    image: sonarqube:10.4-community
this will be addressed in another PR dedicated to the SonarQube upgrade

2024-10-15 07:48 UTC, dedece35 commented on docker-compose.yml
> +    image: sonarqube:10.4-community
why ? it isn't ok with 10.7 if you try

2024-10-22 22:04 UTC, dedece35 approved these changes

2024-11-08 22:59 UTC, merged